name: CI
on:
  push:
    tags:
      - "v*"
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
env:
  ASH_OBAN_CI_OBAN_PRO: "false"
jobs:
  ash-ci:
    uses: ash-project/ash/.github/workflows/ash-ci.yml@main
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    with:
      postgres: true
